//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freestyle.Bladezor.Client.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freestyle.Bladezor.Client.Components.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close blade.
        /// </summary>
        internal static string BladeStack_Close {
            get {
                return ResourceManager.GetString("BladeStack_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Breadcrumb_Home {
            get {
                return ResourceManager.GetString("Breadcrumb_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Drawers_Notifications_Title {
            get {
                return ResourceManager.GetString("Drawers_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MainLayout_Account {
            get {
                return ResourceManager.GetString("MainLayout_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar image.
        /// </summary>
        internal static string MainLayout_AvatarImage {
            get {
                return ResourceManager.GetString("MainLayout_AvatarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainLayout_DrawerHeading_Help {
            get {
                return ResourceManager.GetString("MainLayout_DrawerHeading_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MainLayout_DrawerHeading_Notifications {
            get {
                return ResourceManager.GetString("MainLayout_DrawerHeading_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainLayout_DrawerHeading_Settings {
            get {
                return ResourceManager.GetString("MainLayout_DrawerHeading_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string MainLayout_SignOut {
            get {
                return ResourceManager.GetString("MainLayout_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ModalStack_Close {
            get {
                return ResourceManager.GetString("ModalStack_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string Notifications_ClearAll {
            get {
                return ResourceManager.GetString("Notifications_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close notifications panel.
        /// </summary>
        internal static string Notifications_Close {
            get {
                return ResourceManager.GetString("Notifications_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here, move along..
        /// </summary>
        internal static string Notifications_EmptyState_Description {
            get {
                return ResourceManager.GetString("Notifications_EmptyState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no notifications.
        /// </summary>
        internal static string Notifications_EmptyState_Title {
            get {
                return ResourceManager.GetString("Notifications_EmptyState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Notifications_Group_DefaultTitle {
            get {
                return ResourceManager.GetString("Notifications_Group_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all read.
        /// </summary>
        internal static string Notifications_MarkAllRead {
            get {
                return ResourceManager.GetString("Notifications_MarkAllRead", resourceCulture);
            }
        }
    }
}
